Завдання 1

In [25]:
import numpy as np
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
import pandas as pd


X, y = make_classification(n_samples=600, n_features=10, n_classes=2, random_state=42)
data = pd.DataFrame(X, columns=[f'Feature_{i}' for i in range(1, 11)])
data['Target'] = y
data.head()

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0   0.248887   0.191898  -2.063403  -0.297218  -0.317350   0.941182   
1  -2.854116  -0.403648  -0.643550   1.271347   1.029961  -0.334775   
2   1.129308   0.544220   0.323185  -0.661905   1.283817   1.294986   
3   1.742495   0.072874  -1.143019  -0.134556   0.820158  -0.064689   
4   0.632706  -1.357518   0.324340  -0.809045  -0.532725   0.839664   

   Feature_7  Feature_8  Feature_9  Feature_10  Target  
0   1.025109   0.267986   0.320494    1.948343       1  
1   0.423599  -2.187883  -1.033499   -0.955123       0  
2   0.514063   0.931504   0.605318    0.845803       1  
3  -0.150243   1.069952  -0.162208    0.073197       0  
4  -0.964200   0.703411   0.880846   -0.900671       1

Завдання 2

In [35]:
ZooDf = pd.read_csv("zoo.csv")
ZooDf.head()


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

Завдання 3

In [15]:
def generate_classification_data(samples, features):
    x_rand = np.random.randn(samples, features)
    
    y_rand = (x_rand.sum(axis=1) > 0).astype(int)
    
    data = pd.DataFrame(x_rand, columns=[f'Feature_{i}' for i in range(1, features + 1)])
    data['Class'] = y_rand
    
    return data

df = generate_classification_data(100, 5)
print(df)

    Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Class
0    1.484208   0.948295   2.190970  -1.700515  -0.799502      1
1   -0.109331  -0.269808  -1.904969  -1.687712  -2.348817      0
2    0.452574  -0.106614  -0.994077   1.593384  -0.085845      1
3    0.033582   0.106231   0.983008  -0.600909  -0.080299      1
4   -0.661976  -0.172205   0.139147  -0.054096  -1.485082      0
..        ...        ...        ...        ...        ...    ...
95   1.399773   1.698347  -0.265662   1.574231  -1.027978      1
96   0.930476   0.404886  -0.299445   1.309398   0.052383      1
97   0.140946  -0.124052   0.289770  -0.581092  -0.767819      0
98   0.888722   0.320143   0.626772   0.225660  -0.326155      1
99   1.287356  -2.572362  -0.963055   0.328172  -1.572676      0

[100 rows x 6 columns]


Завдання 4.1 - моделювання для данних згенерованих за допомогою make_classification

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


print("Точність:", accuracy_score(y_test, y_pred))
print("Матриця плутанини:\n", confusion_matrix(y_test, y_pred))
print("Звіт класифікації:\n", classification_report(y_test, y_pred))

plt.show()

Точність: 0.9222222222222223
Матриця плутанини:
 [[87  8]
 [ 6 79]]
Звіт класифікації:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93        95
           1       0.91      0.93      0.92        85

    accuracy                           0.92       180
   macro avg       0.92      0.92      0.92       180
weighted avg       0.92      0.92      0.92       180



Завдання 4.2 - моделювання для данних завантажених з Kaggle

In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


X = ZooDf.drop('class_type', axis=1)
X = ZooDf.drop('animal_name', axis=1)
y = ZooDf['class_type']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


print("Точність:", accuracy_score(y_test, y_pred))
print("Матриця плутанини:\n", confusion_matrix(y_test, y_pred))
print("Звіт класифікації:\n", classification_report(y_test, y_pred))


print(X.dtypes)


Точність: 0.9354838709677419
Матриця плутанини:
 [[15  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  0  0  0  1  2]]
Звіт класифікації:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00         3
           3       0.00      0.00      0.00         1
           4       0.67      1.00      0.80         2
           5       1.00      1.00      1.00         2
           6       0.83      1.00      0.91         5
           7       1.00      0.67      0.80         3

    accuracy                           0.94        31
   macro avg       0.79      0.81      0.79        31
weighted avg       0.92      0.94      0.92        31

hair          int64
feathers      int64
eggs          int64
milk          int64
airborne      int64
aquatic       int64
predator      int64
toothed       int64
backb

c:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.p